DROP TABLE PRODUCT_DETAIL;
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
	PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
	P_NAME VARCHAR2(30) NOT NULL,
	PRICE NUMBER NOT NULL,
	DESCRIPTION VARCHAR2(20)

);

INSERT INTO PRODUCT
VALUES('LT_SS7','삼성노트북',1580000,'이온');

INSERT INTO PRODUCT
VALUES('LT_MA13','맥북에어',1200000,'XCODE4');

INSERT INTO PRODUCT
VALUES('PC_IBM','IBMPC',850000,'WINDOW8');

SELECT * FROM PRODUCT;